apiVersion: apps/v1
kind: Deployment
metadata:
   name: vprodb
   labels:
      app: vprodb
spec:
   replicas: 1
   selector:
      matchLabels:
         app: vprodb
   template:
      metadata:
         labels:
            app: vprodb
      spec:
         containers:
         - name: vprodb
           image: sidnal08/vprofiledb
           imagePullPolicy: Always
           ports:
           - name: vprodb-port
             containerPort: 3306
           volumeMounts:
           - mountPath: /var/lib/mysql
             name: vpro-db-data
           env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                   secretKeyRef:
                      name: dbsecret           
                      key: db-pass
         volumes:
         - name: vpro-db-data
           persistentVolumeClaim:
             claimName: db-pv-claim
         initContainers:
            - name: busybox
              image: busybox:latest
              args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: vpro-db-data
         
