apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  db-user: cm9vdA==
  db-pass: dnByb2RicGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: mqsecret
type: Opaque
data:
  mq-user: Z3Vlc3Q=
  mq-pass: Z3Vlc3Q=